define (require, exports, module) ->
  
  module.exports =
    landing         : '/images/loading.png'
    home            : '/images/home-banner.jpg'
    about           : '/images/banners/about.jpg'
    contact         : '/images/banners/contact.jpg'
    joinus          : '/images/banners/joinus.jpg'
    banner_a        : '/images/hero.jpg'
    banner_b        : '/images/wall-bg.jpg'
    banner_c        : '/images/cc-focus-1.jpg'
    banner_d        : '/images/cc-tech-1.jpg'
    banner_e        : '/images/detail-javaee.jpg'
    banner_f        : '/images/detail-html5.jpg'
    banner_g        : '/images/detail-safety.jpg'
    team_a          : '/images/team/1.png'
    team_b          : '/images/team/2.png'
    team_c          : '/images/team/3.png'
    team_d          : '/images/team/4.png'
    team_e          : '/images/team/5.png'
    team_f          : '/images/team/6.png'
    team_g          : '/images/team/7.png'
    banner_pro_1    : '/images/banners/client-bg-1.jpg'
    banner_pro_2    : '/images/banners/detail-products-customize.jpg'
    banner_pro_3    : '/images/banners/detail-products-online.jpg'
    banner_pro_4    : '/images/banners/detail-products-party3.jpg'
    banner_pro_5    : '/images/banners/oper-bg-1.jpg'
    banner_pro_6    : '/images/banners/site-bg-1.jpg'
    customers_bg_1  : '/images/banners/customers-bg-1.jpg'
    icon_video      : '/images/video-icon.png'

